### ISSUE TITLE
PLUMED version

### ISSUE THREAD

**Issue by maxbonomi** [plumed-nest/plumed-nest#14]
I think the information about the used/declared PLUMED version in each project page is a bit redundant. We have both "PLUMED version" in the header and a "Declared compatibility" column. Since I think most project are done with a single PLUMED version, I would keep only the reference in the header and eliminate the column.

**Comment by maxbonomi** [comment]
why don't we put instead of the "Declared compatibility", a column with a brief description of what this particular plumed input file is doing? In case, where should we parse that information from?

**Comment by maxbonomi** [comment]
still think we can eliminate this column

**Comment by GiovanniBussi** [comment]
I think it is actually good to know which version was used. Let's recall that we don't really test the inputs, but rather check if they can be read. Some features might change across versions.

I would actually provide the information in the yml file similarly to natoms and nreplicas, so that it can be overridden per each input file. We can leave it as optional, so that if it is not provided it becomes something like "unspecified".

Anyway, I agree that it is not so important to go in the master table. What about putting it in the input file page? Something like:

Source: cmyc//cmyc_and_10058_F4/plumed/plumed_master.dat 
Originally used with plumed version: 2.5 
Stable: [raw gzipped stdout](plumed_master.dat.plumed.stdout.txt.gz) - [stderr](plumed_master.dat.plumed.stderr)  
Master: [raw gzipped stdout](plumed_master.dat.plumed_master.stdout.txt.gz) - [stderr](plumed_master.dat.plumed_master.stderr) 

 If you agree with this I can implement it (I am trying to clean up plumed_format since at some point I want to move it to the plumed github repository so that it can be used for making plumed manual as well).

**Comment by maxbonomi** [comment]
I agree with putting it in the input file page and maybe in the header of the Project page, if same version for all input files

**Comment by GiovanniBussi** [comment]
Done. I didn't test what happens when omitting version and/or specifying "per file" version, but I guess everything should work.

I am not sure however "version" is the right name for the yml file. It's not clear "version of what". Perhaps "plumed_version" is better?

**Comment by maxbonomi** [comment]
I would put plumed_version. Don’t remember if Toni already made this point...
