### ISSUE TITLE
input_file problem

### ISSUE THREAD

**Issue by carlocamilloni** [plumed-nest/plumed-nest#29]
It looks like there is a problem in parsing input files name... see 012

**Comment by GiovanniBussi** [comment]
Currently when unzipping there is the assumption that all files are contained in a directory. I mean, the zip structure should be:

````
rootdir/a
rootdir/b
````

and nest.py finds the name of `rootdir`. This is useful when getting repositories from github since they are in a single directory and the name could be long (if you point to a specific commit). In your case there are multiple files. Maybe you can change the nest.py script so that the variable `root=zf.namelist()[0]` can be overridden from the nest.yml configuration file? Something like
````
rootdir: .
````
in your case?

**Comment by carlocamilloni** [comment]
This is fine to me, but then we should say that all content should be included in a single main folder, I was testing alternatives but they look complex and I don’t think is worth adding additional fields

**Comment by GiovanniBussi** [comment]
I thought everyone does zip files with everything in a single directory. Do
you think it is common to have zip files without a single root directory?

For the repos that I added I used github, and there it is natural to
download a full repository as a single zip file (as this
https://www.plumed-nest.org/eggs-19/001/)

Giovanni

**Comment by carlocamilloni** [comment]
I mean, I don’t always do it ;-)

**Comment by GiovanniBussi** [comment]
I guess this is solved now (@carlocamilloni just reopen it if you do not agree)

**Comment by maxbonomi** [comment]
I implemented a solution in nest.py for zips without a root directory. When testing this, I found an unexpected directory in your SAXS egg @carlocamilloni (__MACOSX) at the same level of the root. If you don't want to specify the name of the root directory in plumed_input, I think you need to remove __MACOSX from the zip
