### ISSUE TITLE
plumed_input yml syntax

### ISSUE THREAD

**Issue by maxbonomi** [plumed-nest/plumed-nest#40]
I find this a bit confusing:

plumed_input:
  - path: r108a/plumed-mm.dat
    nreplicas: 2
  - r108a/plumed-orient.dat
  - path: wt/plumed-mm.dat
    nreplicas: 2
  - wt/plumed-orient.dat

I think we should enforce the use of path: even when you don't have other fields for that input file to have a single way to specify the path @GiovanniBussi

**Comment by GiovanniBussi** [comment]
@maxbonomi my point was to avoid forcing `path:` in cases where you do not need the other special options (which are rarely needed). Like this one (017):
````
plumed_input:
  - plumed_metad/metad_20ang.dat
  - plumed_metad/metad_22ang.dat
  - plumed_metad/metad_24ang.dat
  - plumed_metad/metad_26ang.dat
  - plumed_metad/metad_28ang.dat
  - plumed_reweight/reweight_rho_c.dat
````
I don't see the advantage in adding `path:` to each item.

Notice that in your example you can do:
````
plumed_input:
- path: r108a/plumed-mm.dat
  nreplicas: 2
- path: r108a/plumed-orient.dat
- path: wt/plumed-mm.dat
  nreplicas: 2- pathwt/plumed-orient.dat
````
if you find it more readable (I agree it is more readable). I don't think there is any ambiguity. If you want to force some readability we could decide that either all elements in the list are strings (first example) or dictionaries (second example), and that the confusing combination you wrote is forbidden (although I do not see the clear advantage).

Now we are at a stage where it is easy to change all the yml files, but as the syntax becomes more stable I think it is reasonable to have simple defaults. This will make future extensions easier to manage.

For instance, I can imagine that if in the future we allow contributors to fetch from **two** urls, the syntax could be something like
````
url:
  - first.zip
  - second.zip
````
so that `url` can be a list (not sure it is the best choice, it is just a possibility - probably it is not, especially if we go in the direction of forcing the md5 checksum). However, we should not as a consequence convert all the urls to
````
url:
  - single.zip
````
to be lists with one element.

Did I convince you?

**Comment by maxbonomi** [comment]
I think it's a bit of a personal preference. I personally don't like to have two options to do the same thing. But I understand that in this specific case, most of the time you need just the path and the current implementation results in a simpler yml file. So, you (almost) convinced me ;-)
